import sqlite3
conn = sqlite3.connect('jobs.db')
cur = conn.cursor()
cur.execute("SELECT name FROM sqlite_master WHERE type='table'")
print('Tables:', cur.fetchall())
cur.execute("PRAGMA table_info(jobs)")
print('Jobs columns:')
for c in cur.fetchall(): print(c)
cur.execute("SELECT id, title, location, country_name, country_code, salary, salary_min, salary_max, is_remote, source FROM jobs LIMIT 20")
print()
print('Sample jobs:')
for r in cur.fetchall(): print(r)
cur.execute("SELECT country_name, COUNT(*) FROM jobs WHERE country_name IS NOT NULL GROUP BY country_name ORDER BY COUNT(*) DESC")
print()
print('Jobs by country:')
for r in cur.fetchall(): print(r)
cur.execute("SELECT country_name, COUNT(*) FROM jobs WHERE is_remote=1 AND country_name IS NOT NULL GROUP BY country_name ORDER BY COUNT(*) DESC")
print()
print('Remote jobs by country:')
for r in cur.fetchall(): print(r)
cur.execute("SELECT salary, salary_min, salary_max FROM jobs WHERE salary IS NOT NULL LIMIT 20")
print()
print('Sample salaries:')
for r in cur.fetchall(): print(r)
cur.execute("SELECT COUNT(*) FROM jobs")
print()
print('Total jobs:', cur.fetchone()[0])
conn.close()
